### ISSUE TITLE
Read annotation signals

### ISSUE THREAD

**Issue by LiorBanai** [LiorBanai/EDF#8]
Hello,

I would like to use your code in our project and I have two questions:

The project is written to run in .NET Framework 4.7.1 and higner. Would it be possible to compile your project with .NET 4.6 also?
Do I understand correctly that your code defines the class "AnnotationSignal" and "TAL" according to the EDF+ documentation about TALs but does not implement methods for reading EDF+ annotations from a .edf file, only methods for savig them?
The method Reader.ReadAnnotationSignals() mentioned in a note in your code is not defined anywhere. I could not find any other project for C# handling of EDF files including EDF+ annotations and your project seems to be the closest available.

Thank you a lot for your possible reaction!

**Comment by LiorBanai** [comment]
fixed

**Comment by shekharmchallenging** [comment]
Hi Need annotations list with Onset value, Duration need to separate Function

**Comment by shekharmchallenging** [comment]
More Than Two Hour eeg data in edf , Reading  Time its Getting error Exception o type "system outOfMemoryException was thrown  like this
